name: Build

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Prepare environment
        run: |
          rm -rf ./build/*
          mkdir ./build

      - name: Install ares-cli globally
        run: npm install -g @webosose/ares-cli

      - name: Check packaging
        run: ares-package --check

      - name: Build package
        run: ares-package --no-minify --outdir build/ services frontend

      - name: Create manifest for distribution
        run: node tools/gen-manifest.js build/org.jellyfin.webos.manifest.json

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jellyfin_webos
          path: |
            ${{github.workspace}}/build/*

      - name: Upload GitHub Release Artifacts
        uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: 'build/*'
          overwrite: true
